version: '3.8'

services:
  mindmaple_api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mindmaple_db

  mindmaple_db:
    image: postgres:13
    volumes:
      - mindmaple_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  mindmaple_postgres_data:
