version: '3.8'

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://mindmaple:mindmaplepassword@db:5432/mindmaple_db
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=mindmaple
      - POSTGRES_PASSWORD=mindmaplepassword
      - POSTGRES_DB=mindmaple_db
    ports:
      - "5432:5432"

volumes:
  postgres_data:
